<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IN-8YCXH32" name="com.automation.testngexamples.java.TestAnnotations1" tests="3" failures="0" timestamp="11 May 2016 07:38:57 GMT" time="5.023" errors="1">
  <testcase name="testThisShouldFail" time="1.005" classname="com.automation.testngexamples.java.TestAnnotations1">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testThisShouldFail() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testThisShouldFail() didn't finish within the time-out 1000
	at com.automation.testngexamples.java.TestAnnotations1.testThisShouldFail(TestAnnotations1.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testThisShouldFail -->
  <testcase name="testThisShouldPass" time="4.007" classname="com.automation.testngexamples.java.TestAnnotations1"/>
  <testcase name="method1" time="0.011" classname="com.automation.testngexamples.java.TestAnnotations1"/>
</testsuite> <!-- com.automation.testngexamples.java.TestAnnotations1 -->
